---
- name: Install fortune package on CentOS 9
  hosts: webserver
  become: yes

  tasks:
    - name: Install epel-release repository
      dnf:
        name: epel-release
        state: present

    - name: Install fortune package
      dnf:
        name: fortune-mod
        state: present
