---
- name: Install fortune package on Ubuntu
  hosts: 10.10.100.52
  become: yes

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install fortune package
      apt:
        name: fortune
        state: present
