---
- name: File Module
  hosts: webserver

  tasks:
  - name: Creating a file
    file:
      path: /tmp/newfile.txt
      state: touch
      owner: root
      group: root
      mode: 777
  - name: Creating a directory
    file:
      path: /tmp/myfolder
      state: directory
