---
- name: Configure firewall policy
  hosts: fortigate
  connection: httpapi
  gather_facts: no
  vars:
    ansible_network_os: fortinet.fortios.fortios  # Specify the correct network OS here
    access_token: "jt6QNmh0Ngny1mmq3yngkbkyHmzbNs"  # Replace with your actual token
  tasks:
    - name: Create Firewall Policy
      fortios_firewall_policy:
        vdom: "root"
        state: "present"
        access_token: "{{ access_token }}"
        firewall_policy:
          policyid: 53  # Ensure policyid is unique and correctly specified
          name: "Ansible Tower created Lab-Center to WAN Policy"
          srcintf: [{"name": "Lab-Center"}]
          dstintf: [{"name": "virtual-wan-link"}]
          srcaddr: [{"name": "Windows yogi drl servers"}]
          dstaddr: [{"name": "all"}]
          action: "deny"
          schedule: "always"
          service: [{"name": "ALL"}]
          logtraffic: "all"
      register: result

    - name: Debug API Response
      debug:
        var: result
