---
- name: Example playbook using fortinet.fortios collection
  hosts: localhost
  collections:
    - fortinet.fortios
  tasks:
    - name: Task using a module from fortinet.fortios collection
      fortios_firewall_policy:
        vdom: "root"
        access_token: "{{ fortinet_api_key }}"
        state: "present"
        firewall_policy:
          policyid: 1
          name: "Lab-Center to WAN Policy"
          srcintf:
            - name: "Airowire-Lab-Center (Lab-Center)"
          dstintf:
            - name: "virtual-wan-link"
          srcaddr:
            - name: "Windows yogi drl servers"
          dstaddr:
            - name: "all"
          action: "deny"
          schedule: "always"
          service:
            - name: "ALL"
          nat: "disable"
      delegate_to: localhost
