---
- name: Create a firewall policy in Fortinet firewall
  hosts: fortigates
  collections:
    - fortinet.fortios
  tasks:
    - name: Create firewall policy
      fortios_firewall_policy:
        vdom: "root"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        state: "present"
        firewall_policy:
          policyid: 1
          name: "Lab-Center to WAN Policy"
          srcintf:
            - name: "Airowire-Lab-Center (Lab-Center)"
          dstintf:
            - name: "virtual-wan-link"
          srcaddr:
            - name: "Windows yogi drl servers"
          dstaddr:
            - name: "all"
          action: "deny"
          schedule: "always"
          service:
            - name: "ALL"
          nat: "disable"
