- name: Manage FortiGate Device
  hosts: localhost
  collections:
    - fortinet.fortios
  connection: local
  vars:
    vdom: "root"
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 8443
    ansible_httpapi_timeout: 120
    access_token: "w6b4Nqx38bxfdj8Q4p7g331p4ww960"
    firmware_file_path: "/tmp/FGT_40F-v7.4.1.F-build2463-FORTINET.out"
    local_firmware_file_path: "/tmp/FGT_40F-v7.4.1.F-build2463-FORTINET.out"
  tasks:
  - name: Display Variables
    debug:
      msg: 
        vdom: "{{ vdom }}"
        access_token: "{{ access_token }}"
        firmware_file_path: "{{ firmware_file_path }}"
        local_firmware_file_path: "{{ local_firmware_file_path }}"

  - name: Print Current Working Directory
    command: pwd
    register: current_directory
    delegate_to: localhost

  - name: Display Current Working Directory
    debug:
      var: current_directory
    delegate_to: localhost

  - name: Ensure local firmware file is present
    stat:
      path: "{{ local_firmware_file_path }}"
    register: local_firmware_file
    delegate_to: localhost

  - name: Fail if local firmware file is not present
    fail:
      msg: "Local firmware file not found at {{ local_firmware_file_path }}"
    when: not local_firmware_file.stat.exists

  - name: Copy local firmware file to the execution environment
    copy:
      src: "{{ local_firmware_file_path }}"
      dest: "{{ firmware_file_path }}"
    delegate_to: localhost

  - name: Ensure firmware file is present in the execution environment
    stat:
      path: "{{ firmware_file_path }}"
    register: firmware_file
    delegate_to: localhost

  - name: Fail if firmware file is not present in the execution environment
    fail:
      msg: "Firmware file not found at {{ firmware_file_path }}"
    when: not firmware_file.stat.exists

  - name: Update Firmware
    fortios_monitor:
      vdom: "{{ vdom }}"
      selector: 'upgrade.system.firmware'
      params:
        source: "upload"
        filename: "FGT_40F-v7.4.1.F-build2463-FORTINET.out"
        file_content: "{{ lookup('file', firmware_file_path) | string | b64encode }}"
    register: firmware_update_result

  - name: Display Firmware Update Result
    debug:
      var: firmware_update_result
