- name: Manage FortiGate Device
  hosts: all
  collections:
    - fortinet.fortios
  connection: httpapi
  vars:
    vdom: "root"
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 8443
    ansible_httpapi_timeout: 120
    access_token: "w6b4Nqx38bxfdj8Q4p7g331p4ww960"
  tasks:
  - name: Update Firmware
    fortios_monitor:
      vdom: "{{ vdom }}"
      selector: 'upgrade.system.firmware'
      params:
        source: "upload"
        filename: "FGT_40F-v7.4.1.F-build2463-FORTINET.out"
        file_content: "{{ lookup( 'file', '/home/yogesh/FGT_40F-v7.4.1.F-build2463-FORTINET.out') | string | b64encode }}"
