- name: Manage FortiGate Device
  hosts: all
  collections:
    - fortinet.fortios_monitor
  connection: httpapi
  vars:
    vdom: "root"
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 8443
    access_token: "w6b4Nqx38bxfdj8Q4p7g331p4ww960"  # Define your access token here
    firmware_image_path: "/tmp/FGT_40F-v7.4.1.F-build2463-FORTINET.out"  # Path to firmware image
  tasks:
    - name: Upload firmware to FortiGate
      fortinet.fortios_monitor:
        vdom: "{{ vdom }}"
        access_token: "{{ access_token }}"
        selector: 'firmware.upload'
        params:
          firmware_image: "{{ firmware_image_path }}"
      register: firmware_upload_result

    - name: Show firmware upload result
      debug:
        msg: "Firmware upload result: {{ firmware_upload_result }}"
      when: firmware_upload_result is defined

    - name: Initiate firmware upgrade
      fortinet.fortios_monitor:
        vdom: "{{ vdom }}"
        access_token: "{{ access_token }}"
        selector: 'firmware.upgrade'
        params:
          firmware_image: "{{ firmware_image_path }}"
      register: firmware_upgrade_result

    - name: Show firmware upgrade result
      debug:
        msg: "Firmware upgrade result: {{ firmware_upgrade_result }}"
      when: firmware_upgrade_result is defined

    - name: Activate FortiToken
      fortinet.fortios_monitor:
        vdom: "{{ vdom }}"
        access_token: "{{ access_token }}"
        selector: 'activate.user.fortitoken'
        params:
          tokens: '<token string>'  # Replace with your actual token string
      register: fortitoken_result

    - name: Show FortiToken activation result
      debug:
        msg: "FortiToken activation result: {{ fortitoken_result }}"
      when: fortitoken_result is defined

    - name: Reboot This Device
      fortinet.fortios_monitor:
        vdom: "{{ vdom }}"
        access_token: "{{ access_token }}"
        selector: 'system.reboot'
        params:
          event_log_message: 'Reboot Request From Ansible'
      register: reboot_result

    - name: Show reboot result
      debug:
        msg: "Reboot result: {{ reboot_result }}"
      when: reboot_result is defined
