- name: Configure firewall policy
  hosts: fortigate
  collections:
    - fortinet.fortios
  connection: httpapi
  vars:
    vdom: "root"
    ansible_httpapi_use_ssl: no
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 80
  tasks:
    - name: Configure Global attributes
      fortios_system_global:
        vdom: "{{ vdom }}"
        system_global:
          admintimeout: "60"
          hostname: "Yogi_Firewall"
