- name: Configure firewall policy
  hosts: all
  collections:
    - fortinet.fortios
  connection: httpapi
  vars:
    vdom: "root"
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 8443

  tasks:
    - name: Create Firewall Policy
      fortios_firewall_policy:
        vdom: "{{ vdom }}"
        state: "present"
        firewall_policy:
          policyid: 3
          name: "Ansible Tower created Lab-Center to WAN Policy"
          srcintf: [{"name": "Lab-Center"}]
          dstintf: [{"name": "virtual-wan-link"}]
          srcaddr: [{"name": "Windows yogi drl servers"}]
          dstaddr: [{"name": "all"}]
          action: "deny"
          schedule: "always"
          service: [{"name": "ALL"}]
          logtraffic: "all"
      timeout: 60
      register: result

    - name: Debug API Response
      debug:
        var: result
