- name: Configure firewall policy
  hosts: all
  collections:
    - fortinet.fortios
  connection: httpapi
  vars:
    vdom: "root"
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 8443
    ansible_command_timeout: 60

  tasks:
    - name: Configure Global attributes
      fortios_system_global:
        vdom: "{{ vdom }}"
        system_global:
          admintimeout: "60"
          hostname: "YogiAirowire"
